### ISSUE TITLE
Movies sync shows empty folders, tvshows still sync correctly

### ISSUE THREAD

**Issue by it5c0z1mG** [jellyfin/jellycon#324] opened 2024-03-20 00:21 UTC
Kodi xbox retail version omega
Jellyfin for kodi addon with native paths

Since omega update, when kodi updates library from jellyfin, movies folders get scanned but after import kodi shows movies as empty.
Tv seasons are still working fine

Working nexus setup logs:
[kodi.log](https://github.com/jellyfin/jellycon/files/14658143/kodi.log)
[kodi.old.log](https://github.com/jellyfin/jellycon/files/14658144/kodi.old.log)

Broken omega logs:
[kodi.log](https://github.com/jellyfin/jellycon/files/14658146/kodi.log)
[kodi.old.log](https://github.com/jellyfin/jellycon/files/14658147/kodi.old.log)

End of the log seems to show focus issues, no idea if thats the issue or what it is but please help.

(JELLYFIN.jellyfin_kodi.library -> INFO::jellyfin_kodi\library.py:455 --[ sync/2024-03-19T23:35:25z ]
2024-03-19 23:37:28.025 T:5368     info <general>: JELLYFIN.jellyfin_kodi.full_sync -> INFO::jellyfin_kodi\full_sync.py:209 Full sync completed in: 0:01:18
2024-03-19 23:37:28.060 T:5368     info <general>: JELLYFIN.jellyfin_kodi.full_sync -> INFO::jellyfin_kodi\full_sync.py:603 --<[ fullsync ]
2024-03-19 23:37:28.082 T:3368     info <general>: VideoInfoScanner: Starting scan ..
2024-03-19 23:37:32.884 T:5368     info <general>: JELLYFIN.jellyfin_kodi.monitor -> INFO::jellyfin_kodi\monitor.py:42 -->[ kodi scan/video ]
2024-03-19 23:37:35.657 T:3368     info <general>: VideoInfoScanner: Finished scan. Scanning for video info took 7583 ms
2024-03-19 23:37:35.676 T:5368     info <general>: JELLYFIN.jellyfin_kodi.monitor -> INFO::jellyfin_kodi\monitor.py:45 --<[ kodi scan/video ]
2024-03-19 23:37:35.685 T:5552  warning <general>: CGUIMediaWindow::OnMessage - updating in progress
2024-03-19 23:37:35.972 T:5588     info <general>: JELLYFIN -> INFO::jellyfin_kodi\jellyfin\__init__.py:98 ---[ START JELLYFINCLIENT ]---
2024-03-19 23:37:35.982 T:5588     info <general>: JELLYFIN.jellyfin_kodi.entrypoint.default -> INFO::jellyfin_kodi\entrypoint\default.py:72 path:  params: {}
2024-03-19 23:37:36.200 T:5588     info <general>: JELLYFIN.__main__ -> INFO::default.py:25 ---<[ default ]
2024-03-19 23:37:44.896 T:5552    error <general>: Control 55 in window 10025 has been asked to focus, but it can't
2024-03-19 23:37:55.963 T:5552     info <general>: Attempting to default to: 
2024-03-19 23:37:55.963 T:5552     info <general>: Loading skin file: FileManager.xml, load type: KEEP_IN_MEMORY
2024-03-19 23:38:01.305 T:5552    error <general>: Control 18 in window 10129 has been asked to focus, but it can't
2024-03-19 23:38:04.877 T:5552     info <general>: Loading skin file: FileBrowser.xml, load type: KEEP_IN_MEMORY)

**Comment by oddstr13** [comment] 2024-03-20 00:34
This is the wrong repo (there are two Kodi addons).

Duplicate of https://github.com/jellyfin/jellyfin-kodi/issues/808

**Closed by oddstr13** 2024-03-20 00:34 UTC
Labels: bug
