### ISSUE TITLE
Help with Kodi TMDB Helper player configuration

### ISSUE THREAD

**Issue by cremonies** [jellyfin/jellycon#214] opened 2022-09-12 19:24 UTC
TMDB helper has a player config file for EmbyCon and plex. Can one be configured for jellycon?
They are originally json files.
**blank config format**
{
    "name"              : "STR_PLUGINNAME",
    "plugin"            : "STR_PLUGINID",
    "priority"          : 100,
    "assert"            : {
                            "play_movie":       ["title", "year"],
                            "play_episode":     ["showname", "season", "episode"],
                            "search_movie":     ["title"],
                            "search_episode":   ["showname"]
                          },
    "play_movie"        : [
                            "STR_PLUGINMOVIESEARCHURL",
                            {"title": "(?i)^(\\[.*\\])?.*{title}.*(\\[.*\\])?$", "year": "{year}"}
                          ],
    "play_episode"      : [
                            "STR_PLUGINTVSEARCHURL",
                            {"title": "(?i)^(\\[.*\\])?{showname}(\\[.*\\])?$"},
                            {"return": "true", "season": "^{season}$", "episode": "^{episode}$"},
                            {"season": "^{season}$"},
                            {"season": "^{season}$", "episode": "^{episode}$"}
                          ],
    "search_movie"      : [
                            "STR_PLUGINMOVIESEARCHURL",
                            {"keyboard": "{title}"}
                          ],
    "search_episode"    : [
                            "STR_PLUGINTVSEARCHURL",
                            {"keyboard": "{showname}"}
                          ]
}

**embycon example**
{
    "name" : "EmbyCon",
    "plugin" : "plugin.video.embycon",
    "priority" : 200,
    "assert": {"play_episode": ["epid"]},
    "fallback": {"play_movie": "embycon.json search_movie",
                 "play_episode": "embycon.json search_episode",
                 "search_episode": "embycon.parentid.json search_episode"},
    "play_movie" : [
                    "plugin://plugin.video.embycon/?content_type=video&media_type=movies&mode=GET_CONTENT&url=%7Bserver%7D%2Femby%2FUsers%2F%7Buserid%7D%2FItems%3FIncludeItemTypes%3Dmovie%26Recursive%3Dtrue%26fields%3DMediaStreams%26ImageTypeLimit%3D1%26AnyProviderIdEquals%3Dtvdb.{tvdb},imdb.{imdb},tmdb.{tmdb},trakt.{trakt}",
                    {"dialog": "auto"}
                   ],
    "search_movie" : [
                    "plugin://plugin.video.embycon/?content_type=video&mode=GET_CONTENT&media_type=movies&url=%7Bserver%7D%2Femby%2FUsers%2F%7Buserid%7D%2FItems%3FIncludeItemTypes%movie%26IncludeMedia%3Dtrue%26filters%3DIsNotFolder%26fields%3DMediaStreams%26Recursive%3Dtrue%26Years%3D{year}%26ImageTypeLimit%3D1%26Limit%3D16%26searchTerm%3D{title_+}",
                    {"dialog": "auto"}
                   ],
    "play_episode" : [
                      "plugin://plugin.video.embycon/?content_type=video&mode=GET_CONTENT&media_type=episodes&url=%7Bserver%7D%2Femby%2FUsers%2F%7Buserid%7D%2FItems%3FIncludeItemTypes%3Depisode%26filters%3DIsNotFolder%26fields%3DMediaStreams%26Recursive%3Dtrue%26ImageTypeLimit%3D1%26Limit%3D16%26AnyProviderIdEquals%3Dtvdb.{epid}",
                      {"dialog":"auto"}
                    ],
     "search_episode" : [
                      "plugin://plugin.video.embycon/?content_type=video&mode=GET_CONTENT&media_type=episodes&url=%7Bserver%7D%2Femby%2FUsers%2F%7Buserid%7D%2FItems%3FYears%3D{year}%26IncludeItemTypes%3Depisode%26IncludeMedia%3Dtrue%26filters%3DIsNotFolder%26fields%3DMediaStreams%26Recursive%3Dtrue%26ImageTypeLimit%3D1%26MinPremiereDate%3D{premiered}T00:00:00%26MaxPremiereDate%3D{premiered}T23:59:59%26searchTerm%3D{title_escaped+}%26Limit%3D16",
                      {"dialog":"auto"}
                    ]
}

[composite_for_plex.txt](https://github.com/jellyfin/jellycon/files/9551181/composite_for_plex.txt)
[embycon.parentid.txt](https://github.com/jellyfin/jellycon/files/9551182/embycon.parentid.txt)
[embycon.txt](https://github.com/jellyfin/jellycon/files/9551183/embycon.txt)

**Comment by mcarlton00** [comment] 2022-09-12 21:07
I really have no idea what that addon even does, but based on what's already there it seems like you should just be able to replace "embycon" with "jellycon" in those files and have it work.  You may want to give it a try and see what happens.

**Comment by cremonies** [comment] 2022-09-13 00:02
It allows the user to search multiple add-ons for streams.
I did try just replacing embycon. 
When I search for a title I have in jellyfin, it pulls random titles instead.

**Comment by cremonies** [comment] 2022-09-13 01:28
https://github.com/jurialmunkey/plugin.video.themoviedb.helper/wiki/Player-Function#understanding-players

**Comment by cremonies** [comment] 2022-09-13 03:21
> I really have no idea what that addon even does, but based on what's already there it seems like you should just be able to replace "embycon" with "jellycon" in those files and have it work. You may want to give it a try and see what happens.

Should "emby" be changed or removed?

episodes&url=%7Bserver%7D%2Femby%2F

**Comment by mcarlton00** [comment] 2022-09-14 02:06
I'm not sure if that endpoint was actually removed from the server or not, but it probably needs to have `%2Femby` removed (leave one of the %2F values in there in there.  Like this:

`episodes&url=%7Bserver%7D%2FUsers%2F%7Buserid.......`

**Comment by mcarlton00** [comment] 2022-10-01 12:52
Finally had some time to actually look into this instead of blindly guessing.  The problem is that Emby has added a new query option to their API that we don't have, so when it's trying to query by a given id we're instead handing back all items.  This is the query parameter in question: `AnyProviderIdEquals=tvdb.{tvdb},imdb.{imdb},tmdb.{tmdb},trakt.{trakt}`.  It will need some changes here and then a different URL format in the json files for TMDB Helper.

**Comment by cremonies** [comment] 2022-10-01 14:16
That is exactly what it was going for me when trying it. It would return all items. 
The issue I'm having is jellyfin takes over Kodi DB. TMDB Helper has an option to direct play items from Kodi DB instead of searching jellycon or other plugins. 
TMDB Helper does not recognize the DB After jellyfin takes over. 
Interesttingly, emby has updated their Kodi plugin and it does not seem to takeover Kodi DB. TMDB Helper sees the files as local DB and plays them directly.

**Comment by mcarlton00** [comment] 2022-10-03 13:13
If you want to talk about TMDB helper and jellyfin-kodi, probably better to make an issue for it at https://github.com/jellyfin/jellyfin-kodi/issues to keep discussions in their relevant projects.

JellyCon support has been added upstream, so closing this here.

**Closed by mcarlton00** 2022-10-03 13:13 UTC
Labels: enhancement, Upstream
