### ISSUE TITLE
Connecting with jellycon on one kodi profile breaks jellycon on other kodi profiles

### ISSUE THREAD

**Issue by jkrentz** [jellyfin/jellycon#203] opened 2022-08-03 07:10 UTC
**Describe the bug**
Connecting with jellycon on one kodi profile breaks jellycon on other kodi profiles.

**To Reproduce**
1. Configure 2 users in jellyfin. Auth config is usernames & passwords.
2. Create a 2nd profile in kodi. Set the new profile Media Info and Media sources to Separate
3. On 1st kodi profile: Install jellycon and connect as 1st jellyfin user. Observe jellyfin libraries will load.
4. On 2nd kodi profile: Install jellycon and connect as 2nd jellyfin user. Observe jellyfin libraries will load.
5. Return to 1st kodi profile. Attempt to access jellyfin libraries. Observe they will no longer load. Loading flashes and the UI stays on the same screen.

Deleting auth.json and redoing authentication will fix that profile, but breaks the other profile.

**Expected behavior**
Basic jellycon config on separate kodi profiles will not impact each other.

**Logs**
Nothing interesting in the client logs. On a broken profile attempting to open the jellyfin libraries:
```
2022-08-03 00:00:34.177 T:10033    INFO <general>: initializing python engine.
2022-08-03 00:00:35.094 T:10033    INFO <general>: CPythonInvoker(7, /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.jellycon/default.py): script successfully run
2022-08-03 00:00:35.500 T:10033    INFO <general>: Python interpreter stopped
```

The server logs are full of failed challenges:
```
[2022-08-03 07:00:42.425 +00:00] [INF] "CustomAuthentication" was not authenticated. Failure message: "Invalid token."
[2022-08-03 07:00:42.425 +00:00] [INF] "CustomAuthentication" was not authenticated. Failure message: "Invalid token."
[2022-08-03 07:00:42.425 +00:00] [INF] AuthenticationScheme: "CustomAuthentication" was challenged.
[2022-08-03 07:00:42.449 +00:00] [INF] "CustomAuthentication" was not authenticated. Failure message: "Invalid token."
[2022-08-03 07:00:42.449 +00:00] [INF] "CustomAuthentication" was not authenticated. Failure message: "Invalid token."
[2022-08-03 07:00:42.449 +00:00] [INF] AuthenticationScheme: "CustomAuthentication" was challenged.
[2022-08-03 07:00:56.379 +00:00] [INF] "CustomAuthentication" was not authenticated. Failure message: "Invalid token."
[2022-08-03 07:00:56.380 +00:00] [ERR] Error processing request: "Invalid token". URL "GET" "/socket".
[2022-08-03 07:01:02.845 +00:00] [INF] "CustomAuthentication" was not authenticated. Failure message: "Invalid token."
[2022-08-03 07:01:02.845 +00:00] [INF] "CustomAuthentication" was not authenticated. Failure message: "Invalid token."
[2022-08-03 07:01:02.845 +00:00] [INF] AuthenticationScheme: "CustomAuthentication" was challenged.
```

**System (please complete the following information):**
 - OS: Android
 - Jellyfin Version: 10.8.1
 - Kodi Version: 19.3
 - Addon Version: 0.5.5+py3

**Additional context**
This was working previously, I'm not sure what combination of versions was previously functional.
Probably when passwords were still stored in settings.xml

**Comment by mcarlton00** [comment] 2022-08-05 01:06
Duplicate of #192.  The server is rejecting the new user for some reason and I haven't figured out why yet.

**Closed by mcarlton00** 2022-08-05 01:06 UTC
Labels: bug, duplicate
