### ISSUE TITLE
Impossible to connect (new connection)

### ISSUE THREAD

**Issue by Cosmonear** [jellyfin/jellycon#240] opened 2022-11-01 22:58 UTC
**Describe the bug**
My other devices with the long established connection work very well.
The problem is with new connections.
When entering the web address of my server "https://xxx.xxx.com" it says "Jellycon Error. Check the log for more information".
I tried with a local address too, and it doesn't work either. (eg http://192.168.x.x:8096) => Same Kodi logs.

When I enter the web address of my server "https://xxx.xxx.com/" I get to the next step but then a password error occurs. "There was an error logging in"
And the server side logs are not good with two "/" : "//Users/None/Views".

**Kodi Logs**
```
2022-11-01 23:46:04.016 T:21852    INFO <general>: ES: Starting UDP Event server on port 9777
2022-11-01 23:46:04.016 T:21852    INFO <general>: UDP: Listening on port 9777 (ipv6 : false)
2022-11-01 23:46:04.016 T:17348    INFO <general>: JSONRPC Server: Successfully initialized
2022-11-01 23:46:05.641 T:26196   ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'AttributeError'>
                                                   Error Contents: 'str' object has no attribute 'get'
                                                   Traceback (most recent call last):
                                                     File "C:\Users\xxx\AppData\Roaming\Kodi\addons\plugin.video.jellycon\service.py", line 52, in <module>
                                                       check_server()
                                                     File "C:\Users\xxx\AppData\Roaming\Kodi\addons\plugin.video.jellycon\resources\lib\server_detect.py", line 216, in check_server
                                                       code = quick.get('Code')
                                                   AttributeError: 'str' object has no attribute 'get'
                                                   -->End of Python script error report<--
                                                   
2022-11-01 23:46:05.659 T:26196    INFO <general>: Python interpreter stopped
2022-11-01 23:46:07.557 T:20840    INFO <general>: CIRServerSuite::Process: failed to connect to irss, will keep retrying every 5 seconds
2022-11-01 23:46:09.350 T:18744    INFO <general>: CPythonInvoker(1, C:\Users\xxx\AppData\Roaming\Kodi\addons\service.xbmc.versioncheck\resources\lib\runner.py): script successfully run
2022-11-01 23:46:09.354 T:18744    INFO <general>: Python interpreter stopped
```

**System (please complete the following information):**
 - OS: Windows (But I have the same problem on MAC)
 - Jellyfin Version: 10.8.6
 - Kodi Version: 19.4 et 19.2
 - Addon Version: 0.6

I have a Reverse Proxy. Everything works great.

**Comment by mcarlton00** [comment] 2022-11-02 01:48
Duplicate of #236, caused by quick connect being disabled on the server.  It should be fixed in v0.6.1 that just went out

**Closed by mcarlton00** 2022-11-02 01:48 UTC
Labels: bug, duplicate
