### ISSUE TITLE
Jellycon Add On within KODI - Not all libraries show

### ISSUE THREAD

**Issue by apostolostopalidis** [jellyfin/jellycon#149] opened 2022-05-05 00:44 UTC
I have Jellyfin Server 10.7.7 running on my PC, to which I connect to through an Android Box. On this Android Box I have installed the Jellyfin app from the play store and also KODI. I have three libraries scanned in Jellyfin. 

1. Anime (TV Shows), 
2. UFC (Other), 
3. Home Videos (Other)

KODI, Jellycon, and Jellyfin for Android are the latest available. Installed them just today. Jellyfin Android App connects to all 3 but Jellycon within Kodi only shows the Anime libraries as available to connect to. Does it have to do with the type of libraries? Anime is scanned as "TV Shows", while the other two as "Other".

**Comment by mcarlton00** [comment] 2022-05-05 01:07
Dupe of #46 

The TLDR is that Other/Mixed/Whatever their current name is libraries are just awful and supporting them is a pain in the butt, and I haven't had the time or motivation to rework all the pieces that need reworked for them to function.

**Closed by mcarlton00** 2022-05-05 01:07 UTC
Labels: duplicate
