### ISSUE TITLE
Jellycon context menu only shows once

### ISSUE THREAD

**Issue by ltGuillaume** [jellyfin/jellycon#140] opened 2022-03-22 19:09 UTC
**Describe the bug**

Since I moved to Kodi 19.x the context menu does not show up reliably anymore. It only shows up once, after which it is replaced by Kodi's context menu.

**To Reproduce**

1. Go to any JellyCon folder (I mostly go to `plugin://plugin.video.jellycon/?mode=WIDGET_CONTENT&type=nextup_episodes` via a favourite)
1. Open the JellyCon context menu
1. Pick something like Mark Watched/Mark Unwatched (this is not always necessary)  
__Also: Mark Watched/Unwatched never result in visual feedback in the list, until you go back to a parent folder and then enter the folder again__
1. Try to open the context menu again
1. See Kodi's context menu instead of Jellycon's

**System (please complete the following information):**
 - OS: Windows
 - Kodi Version: 19.4
 - Addon Version: 0.4.7+py3

**Comment by mcarlton00** [comment] 2022-04-03 00:00
This looks like it's going to be another one of those.  I can't replicate it.

JellyCon -> Jellyfin Libraries -> Movies -> Movies - Show All

Things I tried:

* Open context menu, close it, open it on the same item
* Open context menu, close it, open it on a different item
* Open context menu, choose an option, open it on the same item
* Open context menu, choose an option, open it on a different item
* Open context menu, choose an option, go back to the previous menu, back into Movies - Show all, open on the same item
* Open context menu, choose an option, go back to the previous menu, back into Movies - Show all, open on a different item

Additionally, mark watched/unwatched immediately updates the list contents to be either the full square, checkmark, or half filled circle depending on watched status without going to another screen.

I also tried going to the nextup widget as well, in the event something was screwy with just that menu.  I got the same results there.

**Comment by ltGuillaume** [comment] 2022-05-23 00:18
Does this help?

```
 INFO <general>: Loading skin file: D:\Programs\Multimedia\Kodi\portable_data\addons\plugin.video.jellycon\resources\skins\default\720p\ActionMenu.xml, load type: LOAD_ON_GUI_INIT
ERROR <general>: Control 3000 in window 13000 has been asked to focus, but it can't
ERROR <general>: D:\Programs\Multimedia\Kodi\portable_data\addons\script.module.urllib3\lib\urllib3\connectionpool.py:1013: InsecureRequestWarning: Unverified HTTPS request is being made to host 'jellyfin.some.domain'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
                   warnings.warn(
                 
ERROR <general>: Skipped 2 duplicate messages..
ERROR <general>: Exception in thread 
ERROR <general>: Thread-4
ERROR <general>: :
                 
ERROR <general>: Traceback (most recent call last):
                 
ERROR <general>:   File "D:\Programs\Multimedia\Kodi\system\python\Lib\threading.py", line 932, in _bootstrap_inner
                 
ERROR <general>:     
ERROR <general>: self.run()
ERROR <general>: 
                 
ERROR <general>:   File "D:\Programs\Multimedia\Kodi\portable_data\addons\plugin.video.jellycon\resources\lib\monitors.py", line 34, in run
                 
ERROR <general>:     
ERROR <general>: show_menu(params)
ERROR <general>: 
                 
ERROR <general>:   File "D:\Programs\Multimedia\Kodi\portable_data\addons\plugin.video.jellycon\resources\lib\functions.py", line 538, in show_menu
                 
ERROR <general>:     
ERROR <general>: mark_item_watched(item_id)
ERROR <general>: 
                 
ERROR <general>:   File "D:\Programs\Multimedia\Kodi\portable_data\addons\plugin.video.jellycon\resources\lib\functions.py", line 218, in mark_item_watched
                 
ERROR <general>:     
ERROR <general>: check_for_new_content()
ERROR <general>: 
                 
ERROR <general>:   File "D:\Programs\Multimedia\Kodi\portable_data\addons\plugin.video.jellycon\resources\lib\tracking.py", line 23, in wrapper
                 
ERROR <general>:     
ERROR <general>: value = func(*args, **kwargs)
ERROR <general>: 
                 
ERROR <general>:   File "D:\Programs\Multimedia\Kodi\portable_data\addons\plugin.video.jellycon\resources\lib\widgets.py", line 194, in check_for_new_content
                 
ERROR <general>:     
ERROR <general>: m.update(last_played_date + last_added_date)
ERROR <general>: 
                 
ERROR <general>: TypeError
ERROR <general>: : 
ERROR <general>: Unicode-objects must be encoded before hashing
```

**Comment by ltGuillaume** [comment] 2022-05-24 20:57
Here's what pops up with debugging on.

First (successful) time pressing 'C' for Jellyfin context menu:
```
DEBUG <general>: Keyboard: scancode: 0x2e, sym: 0x99, unicode: 0x0000, modifier: 0x0
DEBUG <general>: CInputManager::HandleKey: c (0xf043) pressed, action is ContextMenu
DEBUG <general>: CPlayerCoreFactory::GetPlayers(plugin://plugin.video.jellycon/?item_id=????c9bc2dcd61cf1291f511f0784691&mode=PLAY)
 INFO <general>: Loading skin file: DialogContextMenu.xml, load type: KEEP_IN_MEMORY
DEBUG <general>: ------ Window Init (DialogContextMenu.xml) ------
 INFO <general>: JELLYFIN.resources.lib.functions -> DEBUG::resources\lib\functions.py:330 showMenu(): {'item_id': '????c9bc2dcd61cf1291f511f0784691'}
DEBUG <general>: ------ Window Deinit (DialogContextMenu.xml) ------
DEBUG <CAddonSettings[plugin.video.jellycon]>: trying to load setting definitions from old format...
DEBUG <CSettingsManager>: requested setting (password) was not found.
DEBUG <CSettingsManager>: requested setting (saved_user_password_93e54938267fdc2????caefe53d2f8e9) was not found.
DEBUG <CSettingsManager>: requested setting (server_speed_check_data) was not found.
 INFO <general>: JELLYFIN.resources.lib.functions -> DEBUG::resources\lib\functions.py:442 View ID:54 Content type:episodes
 INFO <general>: JELLYFIN.resources.lib.action_menu -> DEBUG::resources\lib\action_menu.py:60 ActionMenu: __init__
 INFO <general>: JELLYFIN.resources.lib.action_menu -> DEBUG::resources\lib\action_menu.py:28 ActionAutoClose Running
 INFO <general>: JELLYFIN.resources.lib.action_menu -> DEBUG::resources\lib\action_menu.py:31 ActionAutoClose time_since_last : 0.0
DEBUG <general>: ------ Window Init (D:\Programs\Multimedia\Kodi\portable_data\addons\plugin.video.jellycon\resources\skins\default\720p\ActionMenu.xml) ------
 INFO <general>: Loading skin file: D:\Programs\Multimedia\Kodi\portable_data\addons\plugin.video.jellycon\resources\skins\default\720p\ActionMenu.xml, load type: LOAD_ON_GUI_INIT
ERROR <general>: Control 3000 in window 13000 has been asked to focus, but it can't
 INFO <general>: JELLYFIN.resources.lib.action_menu -> DEBUG::resources\lib\action_menu.py:66 ActionMenu: onInit
DEBUG <general>: Keyboard: scancode: 0x50, sym: 0x274, unicode: 0x0000, modifier: 0x0
DEBUG <general>: CInputManager::HandleKey: down (0xf081) pressed, action is Down
 INFO <general>: JELLYFIN.resources.lib.action_menu -> DEBUG::resources\lib\action_menu.py:44 ActionAutoClose set_last : 1653423872.2045193
 INFO <general>: JELLYFIN.resources.lib.action_menu -> DEBUG::resources\lib\action_menu.py:92 ActionMenu: onAction: 4
RNING <general>: [WS-Discovery]: The initial search for servers has failed. No servers found.
DEBUG <general>: Keyboard: scancode: 0x50, sym: 0x274, unicode: 0x0000, modifier: 0x0
 INFO <general>: JELLYFIN.resources.lib.action_menu -> DEBUG::resources\lib\action_menu.py:31 ActionAutoClose time_since_last : 0.20702624320983887
DEBUG <general>: Keyboard: scancode: 0x50, sym: 0x274, unicode: 0x0000, modifier: 0x0
DEBUG <general>: CInputManager::HandleKey: down (0xf081) pressed, action is Down
 INFO <general>: JELLYFIN.resources.lib.action_menu -> DEBUG::resources\lib\action_menu.py:44 ActionAutoClose set_last : 1653423872.9459188
 INFO <general>: JELLYFIN.resources.lib.action_menu -> DEBUG::resources\lib\action_menu.py:92 ActionMenu: onAction: 4
DEBUG <general>: Keyboard: scancode: 0x50, sym: 0x274, unicode: 0x0000, modifier: 0x0
DEBUG <general>: Skipped 1 duplicate messages..
DEBUG <general>: CInputManager::HandleKey: down (0xf081) pressed, action is Down
 INFO <general>: JELLYFIN.resources.lib.action_menu -> DEBUG::resources\lib\action_menu.py:44 ActionAutoClose set_last : 1653423873.186198
 INFO <general>: JELLYFIN.resources.lib.action_menu -> DEBUG::resources\lib\action_menu.py:92 ActionMenu: onAction: 4
DEBUG <general>: Keyboard: scancode: 0x50, sym: 0x274, unicode: 0x0000, modifier: 0x0
DEBUG <general>: Skipped 1 duplicate messages..
DEBUG <general>: CInputManager::HandleKey: down (0xf081) pressed, action is Down
 INFO <general>: JELLYFIN.resources.lib.action_menu -> DEBUG::resources\lib\action_menu.py:44 ActionAutoClose set_last : 1653423873.4061983
 INFO <general>: JELLYFIN.resources.lib.action_menu -> DEBUG::resources\lib\action_menu.py:92 ActionMenu: onAction: 4
 INFO <general>: JELLYFIN.resources.lib.action_menu -> DEBUG::resources\lib\action_menu.py:31 ActionAutoClose time_since_last : 0.005000114440917969
DEBUG <general>: Keyboard: scancode: 0x50, sym: 0x274, unicode: 0x0000, modifier: 0x0
DEBUG <general>: Skipped 1 duplicate messages..
DEBUG <general>: CInputManager::HandleKey: down (0xf081) pressed, action is Down
 INFO <general>: JELLYFIN.resources.lib.action_menu -> DEBUG::resources\lib\action_menu.py:44 ActionAutoClose set_last : 1653423873.6661956
 INFO <general>: JELLYFIN.resources.lib.action_menu -> DEBUG::resources\lib\action_menu.py:92 ActionMenu: onAction: 4
DEBUG <general>: Keyboard: scancode: 0x50, sym: 0x274, unicode: 0x0000, modifier: 0x0
DEBUG <general>: Skipped 1 duplicate messages..
DEBUG <general>: CInputManager::HandleKey: down (0xf081) pressed, action is Down
 INFO <general>: JELLYFIN.resources.lib.action_menu -> DEBUG::resources\lib\action_menu.py:44 ActionAutoClose set_last : 1653423874.2366416
 INFO <general>: JELLYFIN.resources.lib.action_menu -> DEBUG::resources\lib\action_menu.py:92 ActionMenu: onAction: 4
DEBUG <general>: Keyboard: scancode: 0x50, sym: 0x274, unicode: 0x0000, modifier: 0x0
 INFO <general>: JELLYFIN.resources.lib.action_menu -> DEBUG::resources\lib\action_menu.py:31 ActionAutoClose time_since_last : 0.17522621154785156
DEBUG <general>: Keyboard: scancode: 0x1c, sym: 0x13, unicode: 0x000d, modifier: 0x0
DEBUG <general>: Keyboard: scancode: 0x1c, sym: 0x13, unicode: 0x0000, modifier: 0x0
DEBUG <general>: CInputManager::HandleKey: return (0xf00d) pressed, action is Select
 INFO <general>: JELLYFIN.resources.lib.action_menu -> DEBUG::resources\lib\action_menu.py:97 ActionMenu: Selected Item: <xbmcgui.ListItem object at 0x000001F67D7D7FC0>
 INFO <general>: JELLYFIN.resources.lib.action_menu -> DEBUG::resources\lib\action_menu.py:47 ActionAutoClose stop_thread called
DEBUG <general>: ------ Window Deinit (D:\Programs\Multimedia\Kodi\portable_data\addons\plugin.video.jellycon\resources\skins\default\720p\ActionMenu.xml) ------
 INFO <general>: JELLYFIN.resources.lib.action_menu -> DEBUG::resources\lib\action_menu.py:44 ActionAutoClose set_last : 1653423874.9462216
 INFO <general>: JELLYFIN.resources.lib.action_menu -> DEBUG::resources\lib\action_menu.py:92 ActionMenu: onAction: 7
 INFO <general>: JELLYFIN.resources.lib.functions -> DEBUG::resources\lib\functions.py:461 Menu Action Selected: mark_unwatched
 INFO <general>: JELLYFIN.resources.lib.functions -> DEBUG::resources\lib\functions.py:229 Mark Item UnWatched: ????c9bc2dcd61cf1291f511f0784691
 INFO <general>: JELLYFIN.resources.lib.widgets -> DEBUG::resources\lib\widgets.py:129 checkForNewContent Called
DEBUG <CAddonSettings[plugin.video.jellycon]>: trying to load setting definitions from old format...
DEBUG <CSettingsManager>: requested setting (password) was not found.
DEBUG <CSettingsManager>: requested setting (saved_user_password_93e54938267fdc2????caefe53d2f8e9) was not found.
DEBUG <CSettingsManager>: requested setting (server_speed_check_data) was not found.
 INFO <general>: JELLYFIN.resources.lib.widgets -> DEBUG::resources\lib\widgets.py:163 last_added_date: 8803f227a0c1e1b418967329c8b25643
 INFO <general>: JELLYFIN.resources.lib.widgets -> DEBUG::resources\lib\widgets.py:188 last_played_date: 2022-05-24T18:45:42.174599Z
 INFO <general>: JELLYFIN.resources.lib.widgets -> DEBUG::resources\lib\widgets.py:191 Current Widget Hash: 
ERROR <general>: Exception in thread 
ERROR <general>: Thread-4
ERROR <general>: :
                 
ERROR <general>: Traceback (most recent call last):
                 
ERROR <general>:   File "D:\Programs\Multimedia\Kodi\system\python\Lib\threading.py", line 932, in _bootstrap_inner
                 
ERROR <general>:     
ERROR <general>: self.run()
ERROR <general>: 
                 
ERROR <general>:   File "D:\Programs\Multimedia\Kodi\portable_data\addons\plugin.video.jellycon\resources\lib\monitors.py", line 34, in run
                 
ERROR <general>:     
ERROR <general>: show_menu(params)
ERROR <general>: 
                 
ERROR <general>:   File "D:\Programs\Multimedia\Kodi\portable_data\addons\plugin.video.jellycon\resources\lib\functions.py", line 541, in show_menu
                 
ERROR <general>:     
ERROR <general>: mark_item_unwatched(item_id)
ERROR <general>: 
                 
ERROR <general>:   File "D:\Programs\Multimedia\Kodi\portable_data\addons\plugin.video.jellycon\resources\lib\functions.py", line 232, in mark_item_unwatched
                 
ERROR <general>:     
ERROR <general>: check_for_new_content()
ERROR <general>: 
                 
ERROR <general>:   File "D:\Programs\Multimedia\Kodi\portable_data\addons\plugin.video.jellycon\resources\lib\tracking.py", line 23, in wrapper
                 
ERROR <general>:     
ERROR <general>: value = func(*args, **kwargs)
ERROR <general>: 
                 
ERROR <general>:   File "D:\Programs\Multimedia\Kodi\portable_data\addons\plugin.video.jellycon\resources\lib\widgets.py", line 194, in check_for_new_content
                 
ERROR <general>:     
ERROR <general>: m.update(last_played_date + last_added_date)
ERROR <general>: 
                 
ERROR <general>: TypeError
ERROR <general>: : 
ERROR <general>: Unicode-objects must be encoded before hashing
ERROR <general>: 
                 
DEBUG <general>: .
 INFO <general>: Skipped 1 duplicate messages..
 INFO <general>: JELLYFIN.resources.lib.action_menu -> DEBUG::resources\lib\action_menu.py:40 ActionAutoClose Exited
```

Second (UNsuccessful) time pressing 'C' for context menu:
```
DEBUG <general>: CInputManager::HandleKey: c (0xf043) pressed, action is ContextMenu
DEBUG <general>: CPlayerCoreFactory::GetPlayers(plugin://plugin.video.jellycon/?item_id=651ed2013fbd9aa3b275313ee461ab61&mode=PLAY)
DEBUG <general>: CPlayerSelectionRule::GetPlayers: considering rule: system rules
DEBUG <general>: CPlayerSelectionRule::GetPlayers: matches rule: system rules
DEBUG <general>: CPlayerCoreFactory::GetPlayers: matched 0 rules with players
DEBUG <general>: CPlayerCoreFactory::GetPlayers: adding videodefaultplayer (VideoPlayer)
DEBUG <general>: CPlayerCoreFactory::GetPlayers: for video=1, audio=0
DEBUG <general>: CPlayerCoreFactory::GetPlayers: for video=1, audio=1
DEBUG <general>: CPlayerCoreFactory::GetPlayers: added 1 players
DEBUG <general>: ------ Window Init (DialogContextMenu.xml) ------
DEBUG <general>: Keyboard: scancode: 0x01, sym: 0x27, unicode: 0x001b, modifier: 0x0
DEBUG <general>: Keyboard: scancode: 0x01, sym: 0x27, unicode: 0x0000, modifier: 0x0
DEBUG <general>: CInputManager::HandleKey: escape (0xf01b) pressed, action is PreviousMenu
DEBUG <general>: ------ Window Deinit (DialogContextMenu.xml) ------
```

**Comment by mcarlton00** [comment] 2022-05-27 01:38
Yes, that helps a lot.  The key was the "simple update check" setting.  It defaults to enabled and I hadn't ever changed it, you have it disabled so it was going down a different code path.

**Comment by ltGuillaume** [comment] 2022-05-27 08:15
Aha! I thought the default was disabled, so I changed it "back" when I was testing some stuff. Would you mind explaining to me what the difference is exactly?

**Comment by mcarlton00** [comment] 2022-05-27 12:59
I'm not sure, really.  When the check is enabled, it seems like it just sets a flag in the local client, while if it's disabled it reaches out to the server and does a check, but only for a single item.  I suspect it may not be working as intended.

https://github.com/jellyfin/jellycon/blob/11705d46f26e1315f8c1d3dbad2eaf9143d1aca6/resources/lib/widgets.py#L128-L201

**Comment by ltGuillaume** [comment] 2022-05-27 13:05
Hmz, so it seems to skip the entire reload from server process. I guess in most cases that isn't an issue.

I'll check again, but I believe I disabled simple update check because when I entered a Jellycon folder, it always showed the locally available list first, and then the whole list was updated with with new info. I'll test this again.

**Closed** 2022-05-28 13:09 UTC
Labels: bug, help wanted
