### ISSUE TITLE
Media dated before 1960 crashes sync

### ISSUE THREAD

**Issue by it5c0z1mG** [jellyfin/jellycon#325] opened 2024-03-20 00:28 UTC
When importing media to the kodi library and items with a date before 1960/1970 freeze the sync to a snail pace

This seems to be an issue with the xbox version of kodi as microsoft doesnt accept dates older than 1960/70

I found a fix for this from another user

Replacing the 'utils.py' file in the addon helper directory fixes this

Here is the file:-

Please add this to the main addon so i dont have to manually add it everytime.
Thank you.

[utils.py.zip](https://github.com/jellyfin/jellycon/files/14658459/utils.py.zip)

**Comment by oddstr13** [comment] 2024-03-20 00:31
Most likely related to https://github.com/jellyfin/jellyfin-kodi/issues/725

**Comment by it5c0z1mG** [comment] 2024-03-20 00:34
> Most likely related to [jellyfin/jellyfin-kodi#725](https://github.com/jellyfin/jellyfin-kodi/issues/725)

Thats the one!! Great find! If theres anyway we can get this pushed into the next update i would be most greatful, this guys fix works perfectly.

**Comment by oddstr13** [comment] 2024-03-20 00:42
Assuming this is for the jf4kodi addon, same as your other issue,
closing as duplicate of https://github.com/jellyfin/jellyfin-kodi/issues/725

I'll see what I get around to, the movie issue with the next version of Kodi has much higher priority, and once those fixes are tested and merged, that alone will likely trigger a release.

**Closed by oddstr13** 2024-03-20 00:42 UTC
Labels: bug

**Comment by it5c0z1mG** [comment] 2024-03-20 00:55
Amazing news, yes you assume correctly j4kodi.

Thought id memtion it now as if you have to rack you head around a fix for one i thought id kill 2 birds with one stone.

I cannot comprehend the effort you must put into this to make it all work so brilliantly. I take my hat off to you! Thank you for all you do.
