### ISSUE TITLE
Cannot install Jellycon

### ISSUE THREAD

**Issue by GioF71** [jellyfin/jellycon#346] opened 2024-09-14 15:38 UTC
**Describe the bug**
I cannot install Jellycon on a fresh install of OSMC on a Pi3. Yesterday I could install it on an equally fresh installation of LibreElec on an Asus Tinkerboard without issue.
From the GUI, I get an error saying that says "Failed to install a dependency".
On the kodi log, I see the following:

```text
2024-09-14 17:32:41.264 T:515     error <general>: CCurlFile::Open - <https://repo.jellyfin.org/releases/client/kodi/plugin.video.jellyfin/resources/icon.png> Failed with code 404:

2024-09-14 17:32:42.500 T:514     error <general>: CAddonInstallJob[plugin.video.jellycon]: failed to find dependency script.module.requests
2024-09-14 17:32:43.087 T:515     error <general>: CCurlFile::Open - <https://repo.jellyfin.org/releases/client/kodi/plugin.video.jellyfin/resources/icon.png> Failed with code 404:
```

**To Reproduce**
Try to install jellycon on a fresh install of kodi/osmc on a pi3

**Expected behavior**
The dependency should be installed without errors.

**Logs**
From the kodi log:

```text
2024-09-14 17:32:41.264 T:515     error <general>: CCurlFile::Open - <https://repo.jellyfin.org/releases/client/kodi/plugin.video.jellyfin/resources/icon.png> Failed with code 404:

2024-09-14 17:32:42.500 T:514     error <general>: CAddonInstallJob[plugin.video.jellycon]: failed to find dependency script.module.requests
2024-09-14 17:32:43.087 T:515     error <general>: CCurlFile::Open - <https://repo.jellyfin.org/releases/client/kodi/plugin.video.jellyfin/resources/icon.png> Failed with code 404:
```

**Screenshots**

**System (please complete the following information):**
 - OS: OSMC
 - Jellyfin Version: latest, but irrelevant, I cannot get to connect to jellyfin, I cannot install the kodi plugin
 - Kodi Version: 21.1
 - Addon Version: 0.8.0-py3

**Additional context**

**Comment by GioF71** [comment] 2024-09-14 15:50
I tried to install all the dependency manually. All installed but one, signals:

```text
2024-09-14 17:49:05.965 T:821     error <general>: CAddonInstallJob[plugin.video.jellycon]: failed to find dependency script.module.addon.signals
2024-09-14 17:49:07.408 T:821     error <general>: CCurlFile::Open - <https://repo.jellyfin.org/releases/client/kodi/plugin.video.jellyfin/resources/icon.png> Failed with code 404:
```

**Comment by GioF71** [comment] 2024-09-14 15:52
And after trying again and again, that plugin finally installed. Don't know why. I have installed the plugin, however for some reasons (intermittent errors) it wasn't an easy task.

**Comment by mcarlton00** [comment] 2024-09-19 22:13
There's nothing we can do about this.  The problem is Kodi's upstream addon mirrors sometimes sending you to a bad mirror and being unable to retrieve dependencies.  Usually it's fixed by just waiting a while and trying again.

**Closed by mcarlton00** 2024-09-19 22:13 UTC
Labels: bug
