### ISSUE TITLE
i keep getting this menu popup randomly 

### ISSUE THREAD

**Issue by aniel300** [jellyfin/jellycon#86] opened 2021-10-05 14:27 UTC
https://i.imgur.com/fk4zzTQ.png

**Comment by mcarlton00** [comment] 2021-10-06 02:57
I suspect this is a duplicate of #81

**Closed by mcarlton00** 2021-10-06 02:57 UTC
Labels: bug, duplicate

**Comment by aniel300** [comment] 2021-10-06 14:47
yes it is, i found the solution https://github.com/faush01/plugin.video.embycon/issues/117
